### ISSUE TITLE
Support for media queries level 5

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#357]
Media queries level 4 are supported, would be nice to support further:

https://www.w3.org/TR/mediaqueries-5/

```css
@media not (width <= -100px) {
  body { background: green; }
}
```

```css
@media (height > -100px) {
  body { background: green; }
}
```
