### ISSUE TITLE
Nested ampersand not resolved correctly

### ISSUE THREAD

**Issue by zakybilfagih** [davesnx/styled-ppx#546]
Nested ampersand doesn't get correctly resolved. Should be related to #545.

```css
font-size: 1px;
& .lola {
  .felipe & {
    display: none;
  }
}
.lola {
  .felipe & {
    display: none;
  }
}

&:first-child {
  .felipe & {
    display: none;
  }
}
:first-child {
  .felipe & {
    display: none;
  }
}
```
```css
.css-6q9o26 { font-size: 1px; } .felipe .css-6q9o26 .lola { display: none; } .css-6q9o26 .felipe .lola { display: none; } .felipe .css-6q9o26:first-child { display: none; } .css-6q9o26 .felipe :first-child { display: none; }
```
```css
margin: 0;
padding: 0;
list-style-type: none;

:first-child {
  .random-class & {
    @media (min-width: 768px) {
      color: green;
    }
  }
}
```
```css
.css-1bd9i22 { margin: 0; padding: 0; list-style-type: none; } @media (min-width: 768px) { .css-1bd9i22 .random-class :first-child { color: #008000; } }
```
